version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-python
    volumes:
      - cont-data:/data
       
  web:
    image: "$DOCKER_CREDENTIALS_USR/sample-python:24july"
    container_name: pythonapp-cont
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - redis-python
    volumes:
      - cont-data:/app


volumes:
  cont-data:
    driver: local

networks:
  redis-python:
    driver: bridge

