version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
 
  web:
    image: sample-python:latest
    container_name: pythonapp-con
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:80"
