# Stage1 Python Builder 
FROM python:3.9 AS builder

WORKDIR /app

COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Stage2 for Runtime
FROM python:3.9-slim

WORKDIR /app

# Copy installed packages
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

# Copy application code from Stage1
COPY --from=builder /app /app

EXPOSE 80

# Define environment variable
ENV NAME=Sample-PythonApp-Slim

CMD ["python", "app.py"]
